### PR TITLE
Fix picky gcc atof in evalresp (fixes #3578)

### LINKED ISSUE #3578: Issue with installing 1.4.2 via pip
I tried to install obspy 1.4.2 via pip, but I am getting the following error:

```obspy/signal/src/evalresp/parse_fctns.c:22:8: error: conflicting types for ‘atof’; have ‘double(void)’
         22 | double atof();
            |        ^~~~
      In file included from /usr/include/features.h:524,
                       from /usr/include/bits/libc-header-start.h:33,
                       from /usr/include/string.h:26,
                       from obspy/signal/src/evalresp/parse_fctns.c:18:
      /usr/include/bits/stdlib-float.h:25:1: note: previous definition of ‘atof’ with type ‘double(const char *)’
         25 | __NTH (atof (const char *__nptr))
            | ^~~~~
      obspy/signal/src/evalresp/parse_fctns.c: In function ‘parse_pz’:
      obspy/signal/src/evalresp/parse_fctns.c:170:51: error: too many arguments to function ‘atof’; expected 0, have 1
        170 |     blkt_ptr->blkt_info.pole_zero.zeros[i].real = atof(field);
            |                                                   ^~~~ ~~~~~
      obspy/signal/src/evalresp/parse_fctns.c:22:8: note: declared here
         22 | double atof();
            |        ^~~~
      obspy/signal/src/evalresp/parse_fctns.c:175:51: error: too many arguments to function ‘atof’; expected 0, have 1
        175 |     blkt_ptr->blkt_info.pole_zero.zeros[i].imag = atof(field);
            |                                                   ^~~~ ~~~~~
      obspy/signal/src/evalresp/parse_fctns.c:22:8: note: declared here
         22 | double atof();
            |        ^~~~
      obspy/signal/src/evalresp/parse_fctns.c:191:51: error: too many arguments to function ‘atof’; expected 0, have 1
        191 |     blkt_ptr->blkt_info.pole_zero.poles[i].real = atof(field);
            |                                                   ^~~~ ~~~~~
      obspy/signal/src/evalresp/parse_fctns.c:22:8: note: declared here
         22 | double atof();
            |        ^~~~
      obspy/signal/src/evalresp/parse_fctns.c:196:51: error: too many arguments to function ‘atof’; expected 0, have 1
        196 |     blkt_ptr->blkt_info.pole_zero.poles[i].imag = atof(field);
            |                                                   ^~~~ ~~~~~
      obspy/signal/src/evalresp/parse_fctns.c:22:8: note: declared here
         22 | double atof();
            |        ^~~~
      obspy/signal/src/evalresp/parse_fctns.c: In function ‘parse_iir_coeff’:
      obspy/signal/src/evalresp/parse_fctns.c:313:42: error: too many arguments to function ‘atof’; expected 0, have 1
        313 |     blkt_ptr->blkt_info.coeff.numer[i] = atof(field);
            |                                          ^~~~ ~~~~~
      obspy/signal/src/evalresp/parse_fctns.c:22:8: note: declared here
         22 | double atof();
            |        ^~~~
      obspy/signal/src/evalresp/parse_fctns.c:323:42: error: too many arguments to function ‘atof’; expected 0, have 1
        323 |     blkt_ptr->blkt_info.coeff.denom[i] = atof(field);
            |                                          ^~~~ ~~~~~
      obspy/signal/src/evalresp/parse_fctns.c:22:8: note: declared here
         22 | double atof();
            |        ^~~~
      obspy/signal/src/evalresp/parse_fctns.c: In function ‘parse_coeff’:
      obspy/signal/src/evalresp/parse_fctns.c:436:41: error: too many arguments to function ‘atof’; expected 0, have 1
        436 |     blkt_ptr->blkt_info.fir.coeffs[i] = atof(field);
            |                                         ^~~~ ~~~~~
      obspy/signal/src/evalresp/parse_fctns.c:22:8: note: declared here
         22 | double atof();
            |        ^~~~
      obspy/signal/src/evalresp/parse_fctns.c: In function ‘parse_list’:
      obspy/signal/src/evalresp/parse_fctns.c:529:48: error: too many arguments to function ‘atof’; expected 0, have 1
        529 |             blkt_ptr->blkt_info.list.freq[i] = atof(field);
            |                                                ^~~~ ~~~~~
      obspy/signal/src/evalresp/parse_fctns.c:22:8: note: declared here
         22 | double atof();
            |        ^~~~
      obspy/signal/src/evalresp/parse_fctns.c:534:47: error: too many arguments to function ‘atof’; expected 0, have 1
        534 |             blkt_ptr->blkt_info.list.amp[i] = atof(field);
            |                                               ^~~~ ~~~~~
      obspy/signal/src/evalresp/parse_fctns.c:22:8: note: declared here
         22 | double atof();
            |        ^~~~
      obspy/signal/src/evalresp/parse_fctns.c:539:48: error: too many arguments to function ‘atof’; expected 0, have 1
        539 |            blkt_ptr->blkt_info.list.phase[i] = atof(field);
            |                                                ^~~~ ~~~~~
      obspy/signal/src/evalresp/parse_fctns.c:22:8: note: declared here
         22 | double atof();
            |        ^~~~
      obspy/signal/src/evalresp/parse_fctns.c:549:48: error: too many arguments to function ‘atof’; expected 0, have 1
        549 |             blkt_ptr->blkt_info.list.freq[i] = atof(field);
            |                                                ^~~~ ~~~~~
      obspy/signal/src/evalresp/parse_fctns.c:22:8: note: declared here
         22 | double atof();
            |        ^~~~
      obspy/signal/src/evalresp/parse_fctns.c:554:47: error: too many arguments to function ‘atof’; expected 0, have 1
        554 |             blkt_ptr->blkt_info.list.amp[i] = atof(field);
            |                                               ^~~~ ~~~~~
      obspy/signal/src/evalresp/parse_fctns.c:22:8: note: declared here
         22 | double atof();
            |        ^~~~
      obspy/signal/src/evalresp/parse_fctns.c:559:48: error: too many arguments to function ‘atof’; expected 0, have 1
        559 |            blkt_ptr->blkt_info.list.phase[i] = atof(field);
            |                                                ^~~~ ~~~~~
      obspy/signal/src/evalresp/parse_fctns.c:22:8: note: declared here
         22 | double atof();
            |        ^~~~
      obspy/signal/src/evalresp/parse_fctns.c: In function ‘parse_generic’:
      obspy/signal/src/evalresp/parse_fctns.c:637:50: error: too many arguments to function ‘atof’; expected 0, have 1
        637 |     blkt_ptr->blkt_info.generic.corner_freq[i] = atof(field);
            |                                                  ^~~~ ~~~~~
      obspy/signal/src/evalresp/parse_fctns.c:22:8: note: declared here
         22 | double atof();
            |        ^~~~
      obspy/signal/src/evalresp/parse_fctns.c:642:51: error: too many arguments to function ‘atof’; expected 0, have 1
        642 |     blkt_ptr->blkt_info.generic.corner_slope[i] = atof(field);
            |                                                   ^~~~ ~~~~~
      obspy/signal/src/evalresp/parse_fctns.c:22:8: note: declared here
         22 | double atof();
            |        ^~~~
      obspy/signal/src/evalresp/parse_fctns.c: In function ‘parse_fir’:
      obspy/signal/src/evalresp/parse_fctns.c:882:41: error: too many arguments to function ‘atof’; expected 0, have 1
        882 |     blkt_ptr->blkt_info.fir.coeffs[i] = atof(field);
            |                                         ^~~~ ~~~~~
      obspy/signal/src/evalresp/parse_fctns.c:22:8: note: declared here
         22 | double atof();
            |        ^~~~
      obspy/signal/src/evalresp/parse_fctns.c: In function ‘in_epoch’:
      obspy/signal/src/evalresp/parse_fctns.c:1341:19: error: too many arguments to function ‘atof’; expected 0, have 1
       1341 |   this_time.sec = atof(start_pos);
            |                   ^~~~ ~~~~~~~~~
      obspy/signal/src/evalresp/parse_fctns.c:22:8: note: declared here
         22 | double atof();
            |        ^~~~
      obspy/signal/src/evalresp/parse_fctns.c:1368:26: error: too many arguments to function ‘atof’; expected 0, have 1
       1368 |         start_time.sec = atof(start_pos);
            |                          ^~~~ ~~~~~~~~~
      obspy/signal/src/evalresp/parse_fctns.c:22:8: note: declared here
         22 | double atof();
            |        ^~~~
      obspy/signal/src/evalresp/parse_fctns.c:1400:26: error: too many arguments to function ‘atof’; expected 0, have 1
       1400 |           end_time.sec = atof(start_pos);
            |                          ^~~~ ~~~~~~~~~
      obspy/signal/src/evalresp/parse_fctns.c:22:8: note: declared here
         22 | double atof();
            |        ^~~~
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
```

Tried 1.4.1. That installed without issues.

Thought I would highlight this issue here.

### PR DESCRIPTION
**Pull request by ThomasLecocq**
### What does this PR do?

Very recent gcc complain about ``double atof`` being too general ; seems like this simple line solves it all (#3578)

### Why was it initiated?  Any relevant Issues?

#3578

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [ ] All tests still pass.
- [x] Significant changes have been added to `CHANGELOG.txt` .

### CODE REVIEW

**Comment by ThomasLecocq** [comment]
should solve #3578

**Comment by filefolder** [comment]
users seem to say this fixes the issue on the newest GCC 15 which is a bit more strict. i can only confirm that it also compatible with lower versions (ie 12).

as this blocks the installation of 1.4.2 on newer systems it would be great to get it through

**Comment by ThomasLecocq** [comment]
it might need to be based on the maintenance branch and not master... I'm not good at such things :-)

File: obspy/signal/src/evalresp/parse_fctns.c [hunk 1]
```diff
@@ -19,7 +19,7 @@
 #include <stdlib.h>
 
 #include "./evresp.h"
-double atof();
```
Comment (QuLogic) [inline obspy/signal/src/evalresp/parse_fctns.c:22]: Is this not in `stdlib.h`? Can we not just delete the prototype?

File: CHANGELOG.txt [hunk 2]
```diff
@@ -73,6 +73,7 @@ Changes:
    * add support for Chebyshev I/II, elliptic and Bessel filters alongside
      the default Butterworth filters (see #3294)
    * fix potential out of bounds array access in AR picker (see #1801)
+   * fix a small issue in evalresp linked to picky new gcc (see #3587)
```
Comment (QuLogic) [inline CHANGELOG.txt]: BTW, should this point to the issue or the PR (they happen to be the same digits...)?

Comment (ThomasLecocq) [reply CHANGELOG.txt]: excellent question, on or the other is fine I guess. Looks like it was mostly the issues in the list, will change.

File: obspy/signal/src/evalresp/parse_fctns.c (hunk 1 above)
Comment (ThomasLecocq) [reply obspy/signal/src/evalresp/parse_fctns.c:22]: no idea... can't test myself on my machines

File: CHANGELOG.txt (hunk 2 above)
Comment (ThomasLecocq) [reply CHANGELOG.txt]: asking the OP to test

File: obspy/signal/src/evalresp/parse_fctns.c (hunk 1 above)
Comment (ThomasLecocq) [reply obspy/signal/src/evalresp/parse_fctns.c:22]: confirmed, adapting & pushing

**Comment by QuLogic** [comment]
I don't know what the current state of CI is (and why it's failing here.)

**Comment by filefolder** [comment]
hmm it looks like the pyshp shapefile code post py3.9 needs updating. i will give this a shot over the weekend 

edit: luckily very silly. `fieldType` became `fieldtype`

**Comment by ThomasLecocq** [comment]
Its done in a ready PR

**Comment by ThomasLecocq** [comment]
#3599
